### ISSUE TITLE
Fix "Rubocop/Performance/StringReplacement" issue in http/helpers.rb

### ISSUE THREAD

**Issue by iaserrat** [iaserrat/roadmapster#15] opened 2017-08-31 16:57 UTC
Use `delete!` instead of `gsub!`.

https://codeclimate.com/github/iaserrat/roadmapster/http/helpers.rb#issue_59a773521e1f110001000021

**Comment by ericboehs** [comment] 2017-10-12 19:42
I think this is a dup of https://github.com/iaserrat/roadmapster/issues/16

**Comment by cristina-9** [comment] 2017-12-09 14:44
Thanks, this was a duplicate of #16 indeed.

**Closed as completed** 2017-12-09 14:43 UTC
Labels: help wanted, Codeclimate
